### ISSUE TITLE
game crash whenever i try to play audio supplied from the "Load Sound File" Node

### ISSUE THREAD

**Issue by CANA-Dan** [amstaddigital/eXiSoundVis#1]
i mean this very overarchingly. this even includes the "start calculate Freq Spectrum" node. using the "spawn sound 2d" does the same behavior as well, so it seems like the data going in is corrupted in some way.
this is what i have. this is being done in an actor. iv also gone and removed quite a few plugins from my project, so if there are any that your plugin relies on, then that could be causing the issue. im also on 4.26 is thats important.
![image](https://user-images.githubusercontent.com/24213630/135711273-3591b7e0-ef04-4b7f-b0a4-4b94a5f01aa2.png)

**Comment by iliags** [comment]
I'm sorry I though I archived this repo already.

This plugin was developed for a very old version of UE4 by eXi and we don't have the intention of continuing development. There is an audio visualizer plugin in UE4, this capability has been available in Niagara for a little while (I think 4.25+), and in UE5 metasounds will make this plugin redundant if it even works. It's fun to toy with but I wouldn't use this for production.
